version: '3'
tasks:
  setup:
    desc: Install tools needed to run Buf
    cmds:
      - go get
      - npm install

  generate:
    desc: Generate the gRPC stubs from Protobuf
    cmds:
      - buf generate